# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

import sys
_b = sys.version_info[0] < 3 and (lambda x: x) or (
        lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
        name='service.proto',
        package='',
        syntax='proto3',
        serialized_pb=
        _b('\n\rservice.proto\x1a&tensorflow/core/framework/tensor.proto\x1a\x1egoogle/protobuf/wrappers.proto\"_\n\tModelSpec\x12\x0c\n\x04name\x18\x01 \x01(\t\x12,\n\x07version\x18\x02 \x01(\x0b\x32\x1b.google.protobuf.Int64Value\x12\x16\n\x0esignature_name\x18\x03 \x01(\t\"\xbc\x01\n\x0ePredictRequest\x12\x1e\n\nmodel_spec\x18\x01 \x01(\x0b\x32\n.ModelSpec\x12+\n\x06inputs\x18\x02 \x03(\x0b\x32\x1b.PredictRequest.InputsEntry\x12\x15\n\routput_filter\x18\x03 \x03(\t\x1a\x46\n\x0bInputsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.tensorflow.TensorProto:\x02\x38\x01\"\x87\x01\n\x0fPredictResponse\x12,\n\x06result\x18\x01 \x03(\x0b\x32\x1c.PredictResponse.ResultEntry\x1a\x46\n\x0bResultEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.tensorflow.TensorProto:\x02\x38\x01\x32\x35\n\x05Model\x12,\n\x07Predict\x12\x0f.PredictRequest\x1a\x10.PredictResponseb\x06proto3'
           ),
        dependencies=[
                tensorflow_dot_core_dot_framework_dot_tensor__pb2.DESCRIPTOR,
                google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,
        ])

_MODELSPEC = _descriptor.Descriptor(
        name='ModelSpec',
        full_name='ModelSpec',
        filename=None,
        file=DESCRIPTOR,
        containing_type=None,
        fields=[
                _descriptor.FieldDescriptor(
                        name='name',
                        full_name='ModelSpec.name',
                        index=0,
                        number=1,
                        type=9,
                        cpp_type=9,
                        label=1,
                        has_default_value=False,
                        default_value=_b("").decode('utf-8'),
                        message_type=None,
                        enum_type=None,
                        containing_type=None,
                        is_extension=False,
                        extension_scope=None,
                        options=None,
                        file=DESCRIPTOR),
                _descriptor.FieldDescriptor(
                        name='version',
                        full_name='ModelSpec.version',
                        index=1,
                        number=2,
                        type=11,
                        cpp_type=10,
                        label=1,
                        has_default_value=False,
                        default_value=None,
                        message_type=None,
                        enum_type=None,
                        containing_type=None,
                        is_extension=False,
                        extension_scope=None,
                        options=None,
                        file=DESCRIPTOR),
                _descriptor.FieldDescriptor(
                        name='signature_name',
                        full_name='ModelSpec.signature_name',
                        index=2,
                        number=3,
                        type=9,
                        cpp_type=9,
                        label=1,
                        has_default_value=False,
                        default_value=_b("").decode('utf-8'),
                        message_type=None,
                        enum_type=None,
                        containing_type=None,
                        is_extension=False,
                        extension_scope=None,
                        options=None,
                        file=DESCRIPTOR),
        ],
        extensions=[],
        nested_types=[],
        enum_types=[],
        options=None,
        is_extendable=False,
        syntax='proto3',
        extension_ranges=[],
        oneofs=[],
        serialized_start=89,
        serialized_end=184,
)

_PREDICTREQUEST_INPUTSENTRY = _descriptor.Descriptor(
        name='InputsEntry',
        full_name='PredictRequest.InputsEntry',
        filename=None,
        file=DESCRIPTOR,
        containing_type=None,
        fields=[
                _descriptor.FieldDescriptor(
                        name='key',
                        full_name='PredictRequest.InputsEntry.key',
                        index=0,
                        number=1,
                        type=9,
                        cpp_type=9,
                        label=1,
                        has_default_value=False,
                        default_value=_b("").decode('utf-8'),
                        message_type=None,
                        enum_type=None,
                        containing_type=None,
                        is_extension=False,
                        extension_scope=None,
                        options=None,
                        file=DESCRIPTOR),
                _descriptor.FieldDescriptor(
                        name='value',
                        full_name='PredictRequest.InputsEntry.value',
                        index=1,
                        number=2,
                        type=11,
                        cpp_type=10,
                        label=1,
                        has_default_value=False,
                        default_value=None,
                        message_type=None,
                        enum_type=None,
                        containing_type=None,
                        is_extension=False,
                        extension_scope=None,
                        options=None,
                        file=DESCRIPTOR),
        ],
        extensions=[],
        nested_types=[],
        enum_types=[],
        options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(),
                                          _b('8\001')),
        is_extendable=False,
        syntax='proto3',
        extension_ranges=[],
        oneofs=[],
        serialized_start=305,
        serialized_end=375,
)

_PREDICTREQUEST = _descriptor.Descriptor(
        name='PredictRequest',
        full_name='PredictRequest',
        filename=None,
        file=DESCRIPTOR,
        containing_type=None,
        fields=[
                _descriptor.FieldDescriptor(
                        name='model_spec',
                        full_name='PredictRequest.model_spec',
                        index=0,
                        number=1,
                        type=11,
                        cpp_type=10,
                        label=1,
                        has_default_value=False,
                        default_value=None,
                        message_type=None,
                        enum_type=None,
                        containing_type=None,
                        is_extension=False,
                        extension_scope=None,
                        options=None,
                        file=DESCRIPTOR),
                _descriptor.FieldDescriptor(
                        name='inputs',
                        full_name='PredictRequest.inputs',
                        index=1,
                        number=2,
                        type=11,
                        cpp_type=10,
                        label=3,
                        has_default_value=False,
                        default_value=[],
                        message_type=None,
                        enum_type=None,
                        containing_type=None,
                        is_extension=False,
                        extension_scope=None,
                        options=None,
                        file=DESCRIPTOR),
                _descriptor.FieldDescriptor(
                        name='output_filter',
                        full_name='PredictRequest.output_filter',
                        index=2,
                        number=3,
                        type=9,
                        cpp_type=9,
                        label=3,
                        has_default_value=False,
                        default_value=[],
                        message_type=None,
                        enum_type=None,
                        containing_type=None,
                        is_extension=False,
                        extension_scope=None,
                        options=None,
                        file=DESCRIPTOR),
        ],
        extensions=[],
        nested_types=[
                _PREDICTREQUEST_INPUTSENTRY,
        ],
        enum_types=[],
        options=None,
        is_extendable=False,
        syntax='proto3',
        extension_ranges=[],
        oneofs=[],
        serialized_start=187,
        serialized_end=375,
)

_PREDICTRESPONSE_RESULTENTRY = _descriptor.Descriptor(
        name='ResultEntry',
        full_name='PredictResponse.ResultEntry',
        filename=None,
        file=DESCRIPTOR,
        containing_type=None,
        fields=[
                _descriptor.FieldDescriptor(
                        name='key',
                        full_name='PredictResponse.ResultEntry.key',
                        index=0,
                        number=1,
                        type=9,
                        cpp_type=9,
                        label=1,
                        has_default_value=False,
                        default_value=_b("").decode('utf-8'),
                        message_type=None,
                        enum_type=None,
                        containing_type=None,
                        is_extension=False,
                        extension_scope=None,
                        options=None,
                        file=DESCRIPTOR),
                _descriptor.FieldDescriptor(
                        name='value',
                        full_name='PredictResponse.ResultEntry.value',
                        index=1,
                        number=2,
                        type=11,
                        cpp_type=10,
                        label=1,
                        has_default_value=False,
                        default_value=None,
                        message_type=None,
                        enum_type=None,
                        containing_type=None,
                        is_extension=False,
                        extension_scope=None,
                        options=None,
                        file=DESCRIPTOR),
        ],
        extensions=[],
        nested_types=[],
        enum_types=[],
        options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(),
                                          _b('8\001')),
        is_extendable=False,
        syntax='proto3',
        extension_ranges=[],
        oneofs=[],
        serialized_start=443,
        serialized_end=513,
)

_PREDICTRESPONSE = _descriptor.Descriptor(
        name='PredictResponse',
        full_name='PredictResponse',
        filename=None,
        file=DESCRIPTOR,
        containing_type=None,
        fields=[
                _descriptor.FieldDescriptor(
                        name='result',
                        full_name='PredictResponse.result',
                        index=0,
                        number=1,
                        type=11,
                        cpp_type=10,
                        label=3,
                        has_default_value=False,
                        default_value=[],
                        message_type=None,
                        enum_type=None,
                        containing_type=None,
                        is_extension=False,
                        extension_scope=None,
                        options=None,
                        file=DESCRIPTOR),
        ],
        extensions=[],
        nested_types=[
                _PREDICTRESPONSE_RESULTENTRY,
        ],
        enum_types=[],
        options=None,
        is_extendable=False,
        syntax='proto3',
        extension_ranges=[],
        oneofs=[],
        serialized_start=378,
        serialized_end=513,
)

_MODELSPEC.fields_by_name[
        'version'].message_type = google_dot_protobuf_dot_wrappers__pb2._INT64VALUE
_PREDICTREQUEST_INPUTSENTRY.fields_by_name[
        'value'].message_type = tensorflow_dot_core_dot_framework_dot_tensor__pb2._TENSORPROTO
_PREDICTREQUEST_INPUTSENTRY.containing_type = _PREDICTREQUEST
_PREDICTREQUEST.fields_by_name['model_spec'].message_type = _MODELSPEC
_PREDICTREQUEST.fields_by_name[
        'inputs'].message_type = _PREDICTREQUEST_INPUTSENTRY
_PREDICTRESPONSE_RESULTENTRY.fields_by_name[
        'value'].message_type = tensorflow_dot_core_dot_framework_dot_tensor__pb2._TENSORPROTO
_PREDICTRESPONSE_RESULTENTRY.containing_type = _PREDICTRESPONSE
_PREDICTRESPONSE.fields_by_name[
        'result'].message_type = _PREDICTRESPONSE_RESULTENTRY
DESCRIPTOR.message_types_by_name['ModelSpec'] = _MODELSPEC
DESCRIPTOR.message_types_by_name['PredictRequest'] = _PREDICTREQUEST
DESCRIPTOR.message_types_by_name['PredictResponse'] = _PREDICTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModelSpec = _reflection.GeneratedProtocolMessageType(
        'ModelSpec',
        (_message.Message, ),
        dict(DESCRIPTOR=_MODELSPEC,
             __module__='service_pb2'
             # @@protoc_insertion_point(class_scope:ModelSpec)
             ))
_sym_db.RegisterMessage(ModelSpec)

PredictRequest = _reflection.GeneratedProtocolMessageType(
        'PredictRequest',
        (_message.Message, ),
        dict(
                InputsEntry=_reflection.GeneratedProtocolMessageType(
                        'InputsEntry',
                        (_message.Message, ),
                        dict(DESCRIPTOR=_PREDICTREQUEST_INPUTSENTRY,
                             __module__='service_pb2'
                             # @@protoc_insertion_point(class_scope:PredictRequest.InputsEntry)
                             )),
                DESCRIPTOR=_PREDICTREQUEST,
                __module__='service_pb2'
                # @@protoc_insertion_point(class_scope:PredictRequest)
        ))
_sym_db.RegisterMessage(PredictRequest)
_sym_db.RegisterMessage(PredictRequest.InputsEntry)

PredictResponse = _reflection.GeneratedProtocolMessageType(
        'PredictResponse',
        (_message.Message, ),
        dict(
                ResultEntry=_reflection.GeneratedProtocolMessageType(
                        'ResultEntry',
                        (_message.Message, ),
                        dict(DESCRIPTOR=_PREDICTRESPONSE_RESULTENTRY,
                             __module__='service_pb2'
                             # @@protoc_insertion_point(class_scope:PredictResponse.ResultEntry)
                             )),
                DESCRIPTOR=_PREDICTRESPONSE,
                __module__='service_pb2'
                # @@protoc_insertion_point(class_scope:PredictResponse)
        ))
_sym_db.RegisterMessage(PredictResponse)
_sym_db.RegisterMessage(PredictResponse.ResultEntry)

_PREDICTREQUEST_INPUTSENTRY.has_options = True
_PREDICTREQUEST_INPUTSENTRY._options = _descriptor._ParseOptions(
        descriptor_pb2.MessageOptions(), _b('8\001'))
_PREDICTRESPONSE_RESULTENTRY.has_options = True
_PREDICTRESPONSE_RESULTENTRY._options = _descriptor._ParseOptions(
        descriptor_pb2.MessageOptions(), _b('8\001'))

_MODEL = _descriptor.ServiceDescriptor(
        name='Model',
        full_name='Model',
        file=DESCRIPTOR,
        index=0,
        options=None,
        serialized_start=515,
        serialized_end=568,
        methods=[
                _descriptor.MethodDescriptor(
                        name='Predict',
                        full_name='Model.Predict',
                        index=0,
                        containing_service=None,
                        input_type=_PREDICTREQUEST,
                        output_type=_PREDICTRESPONSE,
                        options=None,
                ),
        ])
_sym_db.RegisterServiceDescriptor(_MODEL)

DESCRIPTOR.services_by_name['Model'] = _MODEL

# @@protoc_insertion_point(module_scope)
