# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: service.proto
# plugin: grpclib.plugin.main
import abc

import grpclib.const
import grpclib.client

import tensorflow.core.framework.tensor_pb2
import service_pb2


class ModelBase(abc.ABC):

    @abc.abstractmethod
    async def Infer(self, stream):
        pass

    def __mapping__(self):
        return {
            '/Model/Infer': grpclib.const.Handler(
                self.Infer,
                grpclib.const.Cardinality.UNARY_UNARY,
                service_pb2.ModelQuery,
                service_pb2.ModelResult,
            ),
        }


class ModelStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.Infer = grpclib.client.UnaryUnaryMethod(
            channel,
            '/Model/Infer',
            service_pb2.ModelQuery,
            service_pb2.ModelResult,
        )
