# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import service_pb2 as service__pb2


class ModelStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Infer = channel.unary_unary(
        '/Model/Infer',
        request_serializer=service__pb2.HelloRequest.SerializeToString,
        response_deserializer=service__pb2.HelloResponse.FromString,
        )


class ModelServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Infer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

def add_ModelServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Infer': grpc.unary_unary_rpc_method_handler(
          servicer.Infer,
          request_deserializer=service__pb2.HelloRequest.FromString,
          response_serializer=service__pb2.HelloResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Model', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
